SubmitEvent.submitter & FormData(form, submitter)
naja-js/naja pull request #402
Opened 2024-05-17 11:40 UTC by filiphlm

Solves #401. No polyfill(s) included.

2024-05-17 11:49 UTC, filiphlm commented on src/core/UIHandler.ts
>  		}
BTW: This looks suspicious to me. Shouldn't it be more like this?

```typescript
if (element.matches(selectors)) {
	bindElement(element);
} else {
	const elements = element.querySelectorAll(selectors);
	elements.forEach((element) => bindElement(element));
}
```
(The same applies to form binding below.)

2024-05-28 13:01 UTC, jiripudil requested changes
Thanks, I really like how this simplifies things. I just have a few suggestions regarding the BC and ergonomics of the API

2024-05-29 16:57 UTC, filiphlm commented on src/core/UIHandler.ts
>  		}
Done.

2024-05-29 17:01 UTC, filiphlm commented on src/core/UIHandler.ts
> +	public async submitForm(form: HTMLFormElement, options: Options = {}, event?: SubmitEvent): Promise<Payload> {
I tried: https://github.com/naja-js/naja/pull/402/commits/1b0b2d2518a81aadf49913515c8d218441411d1b

The bottom line is: No `SubmitEvent`, no `SubmitEvent.submitter`. If I'm not mistaken, with a missing or non-standard event (ie anything other than `SubmitEvent`) there will be no change from the previous (pre-PR) behavior. Are you OK with that?

2024-05-29 17:08 UTC, filiphlm commented on src/core/UIHandler.ts
> +	public async clickElement(element: HTMLAnchorElement, options: Options = {}, event?: MouseEvent): Promise<Payload> {
[Maybe this way?](https://github.com/naja-js/naja/pull/402/commits/dfe8ddebc26935aeb5d65616fc296858d75c0f52)

2024-07-07 10:28 UTC, jiripudil approved these changes

2024-07-07 10:29 UTC, merged

2024-07-07 10:39 UTC, jiripudil commented
Hi, sorry this took me so long. I've been having a downswing in terms of time and energy that I'm willing to dedicate to OSS recently.

While reviewing the code, I've had some more thoughts on how to improve its type safety. I took the liberty of implementing the ideas myself, because I didn't want you to have to wait another month for me to come back to this.

I really appreciate the good work you've put into this, and I'm looking forward to your future contributions!